"""Asset resolver: turns AssetNeeds into treated, QA-checked assets with provenance records."""

from __future__ import annotations

import io
import json
from pathlib import Path

from PIL import Image

from deckforge.assets import qa
from deckforge.assets.cache import HttpGet, http_get
from deckforge.assets.needs import AssetNeed, AssetRecord
from deckforge.assets.sources import geo, icons, procedural, stock
from deckforge.assets.sources.generate import ImageBrief, TextToImageClient
from deckforge.assets.treatment import duotone, smart_crop
from deckforge.tokens import Theme

ROLE_STYLE = {"cover": "light_arcs", "divider": "aurora", "band": "motion_streaks",
              "panel": "motion_streaks", "backdrop": "light_planes", "inline": "aurora"}


def _png_bytes(img: Image.Image) -> bytes:
    buf = io.BytesIO()
    img.save(buf, "PNG")
    return buf.getvalue()


class AssetResolver:
    def __init__(self, theme: Theme, *, connected: bool = True, stock_sources=None,
                 t2i: TextToImageClient | None = None, get: HttpGet = http_get):
        self.theme = theme
        self.connected = connected
        self.get = get
        self.stock = [s for s in (stock_sources if stock_sources is not None else
                                  [stock.PexelsSource(get=get), stock.UnsplashSource(get=get)]) if s.available]
        self.t2i = t2i if t2i is not None else TextToImageClient()
        self.records: list[AssetRecord] = []
        self._hashes: list[int] = []
        self._countries = None

    # ------------------------------------------------------------------ palettes
    def _palette(self, style: str) -> tuple[str, ...]:
        t = self.theme
        return {
            "light_arcs": t.glow,
            "aurora": (t.glow[0], t.glow[1], t.accent2),
            "motion_streaks": (t.glow[0], "#FF6B3D", "#EAF2FF"),
            "light_planes": ("#C9CEDB", "#DDE1EA", "#F7F8FB"),
            "contours": (t.paper, "#DCE1EA"),
        }[style]

    def _record(self, need, source, licence, img_or_bytes, **kw) -> AssetRecord:
        data = img_or_bytes if isinstance(img_or_bytes, bytes) else _png_bytes(img_or_bytes)
        rec = AssetRecord(need=need, source=source, licence=licence, sha256=AssetRecord.digest(data), **kw)
        self.records.append(rec)
        return rec

    # ------------------------------------------------------------------ resolvers
    def background(self, need: AssetNeed) -> Image.Image:
        style = need.style or ROLE_STYLE[need.role]
        img = procedural.STYLES[style](w=need.width_px, h=need.height_px, palette=self._palette(style),
                                       seed=need.seed)
        result = qa.check(img, min_width=min(need.width_px, 1280), seen_hashes=self._hashes)
        self._hashes.append(result.hash)
        self._record(need, f"procedural:{style}", "Owned (generated by DeckForge code)", img,
                     qa=result.as_dict())
        return img

    def photo(self, need: AssetNeed, brief: ImageBrief, query: str | None = None) -> Image.Image:
        """Generate locally, else fetch licensed stock, else fall back to a procedural background."""
        tried: list[str] = []
        aspect = need.width_px / need.height_px
        candidates = []
        if self.t2i.available:
            tried.append("t2i")
            try:
                img, meta = self.t2i.generate(brief, seed=need.seed)
                candidates.append((img, f"t2i:{meta['model']}", "Generated (Apache-2.0 model)", None, None, True))
            except OSError:
                pass
        if self.connected:
            for src in self.stock:
                tried.append(src.name)
                try:
                    for cand in src.search(query or brief.subject, n=5)[:3]:
                        img = Image.open(io.BytesIO(stock.download(cand, self.get))).convert("RGB")
                        candidates.append((img, src.name, cand.licence, cand.attribution, cand.page_url, False))
                except OSError:
                    continue
        for img, source, licence, attribution, url, generated in candidates:
            treated = self._treat_photo(img, aspect, need)
            result = qa.check(treated, min_width=min(need.width_px, 1280), min_sharpness=40,
                              seen_hashes=self._hashes)
            if result.passed:
                self._hashes.append(result.hash)
                self._record(need, source, licence, treated, attribution=attribution, url=url,
                             ai_generated=generated, fallback_from=tried[:-1], qa=result.as_dict())
                return treated
        fallback = need.model_copy(update={"kind": "background", "style": need.style if need.style in
                                           procedural.STYLES else ROLE_STYLE[need.role]})
        img = self.background(fallback)
        self.records[-1].fallback_from = tried
        return img

    def _treat_photo(self, img: Image.Image, aspect: float, need: AssetNeed) -> Image.Image:
        cropped = smart_crop(img, aspect, avoid=need.text_zone)
        resized = cropped.resize((need.width_px, need.height_px), Image.LANCZOS)
        return duotone(resized, self.theme.glow[0], "#F4F7FB", strength=0.45)   # brand colour grading

    def icon(self, name: str, color: str, px: int = 256, icon_set: str = "lucide") -> Image.Image:
        img, url = icons.icon_png(name, color, px, icon_set, get=self.get)
        lic, attr = icons.ICON_SETS[icon_set][1:]
        self._record(AssetNeed(kind="icon", subject=name, style=icon_set, width_px=px, height_px=px),
                     icon_set, lic, img, attribution=attr, url=url)
        return img

    def flag(self, code: str, width_px: int = 240) -> Image.Image:
        img, url = icons.flag_png(code, width_px, get=self.get)
        self._record(AssetNeed(kind="flag", subject=code, width_px=width_px, height_px=int(width_px * 0.75)),
                     "flag-icons", icons.FLAGS[1], img, attribution=icons.FLAGS[2], url=url)
        return img

    def countries(self) -> dict[str, geo.Country]:
        if self._countries is None:
            data = self.get(geo.NATURAL_EARTH_110M, None)
            self._countries = geo.load_countries(lambda url, headers: data)
            self._record(AssetNeed(kind="map", subject="world_110m"), "natural-earth", geo.LICENCE, data,
                         url=geo.NATURAL_EARTH_110M)
        return self._countries

    def manifest(self, path: str | Path) -> Path:
        path = Path(path)
        path.write_text(json.dumps([r.model_dump(mode="json") for r in self.records], indent=2))
        return path
